In [3]:
import numpy as np

In [4]:
#ques1
#convert the list to array and print it
lis=[1,2,3,4,5]
arr=np.array(lis)
print(arr)

[1 2 3 4 5]


In [5]:
#ques2
#print the first element 
print(" first element : ",arr[0])
#print the last element 
print(" last element : ",arr[len(arr)-1])
#multiply all the elements by 2 and then print the element 
print(" After multiplying by 2  : ",arr*2)

 first element :  1
 last element :  5
 After multiplying by 2  :  [ 2  4  6  8 10]


In [6]:
#ques3
#define 10 zeros in the array and then print it
arra=np.zeros((10,),dtype=int)
print("array of 10 zeroes")
print(arra)
#define 10 ones in the array and then print it
print("array of 10 ones")
arra=np.ones((10,),dtype=int)
print(arra)
#define 10 fives in the array and then print it
print("array of 10 fives")
arra=np.ones((10,),dtype=int)*5
print(arra)

array of 10 zeroes
[0 0 0 0 0 0 0 0 0 0]
array of 10 ones
[1 1 1 1 1 1 1 1 1 1]
array of 10 fives
[5 5 5 5 5 5 5 5 5 5]


In [8]:
#ques4
#define numbers from 2 to 10 in a array and then reshape it to 3,3
arr=np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
