In [1]:
# ques1
# calculate total revenue generated by 2 product stores
import numpy as np
pro1=np.array([500,600,700,550])
pro2=np.array([450,700,800,600])
print(pro1+pro2)


[ 950 1300 1500 1150]


In [2]:
#ques2
# calculate profit
revenue=np.array([10000,12000,11000,10500])
expense=np.array([4000,5000,4500,4800])
print(revenue-expense)


[6000 7000 6500 5700]


In [3]:
# ques3
# calculate items which are unavailable
inventory=np.array([10,0,5,0,20,0])
print(*np.where(inventory==0))


[1 3 5]


In [4]:
# ques4
# calculate total cost of items
qty=np.array([2,3,4,1])
price_per_item=np.array([10.0,5.0,8.0,12.0],dtype='int')       
print(qty*price_per_item)


[20 15 32 12]


In [6]:
#ques5
#calculate quantity sum
c=np.sum(qty)
print(c)

10
